#生产环境
---
##日志等级配置
#logging:
#  level:
#    root: error
#---
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/kwmanage?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: 12345678
#    # 初始化大小，最小，最大
#    initialSize: 1
#    minIdle: 3
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    filters: stat,wall,slf4j